name: Simulate Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select a environment
        options: 
        - staging
        - production
      tag:
        description: Informs a tags
        required: true

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
    - name: Rollback Staging
      if: ${{ inputs.environment }} == 'staging'
      run: echo "execute staging rollback of ${{ inputs.tag }}..."

    steps:
    - name: Rollback Production
      if: ${{ inputs.environment }} == 'production'
      run: echo "execute production rollback of ${{ inputs.tag }}..."
