version: '3.9'
services:
  app:
    build:
      context: .
      target: base
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - mix_deps:/app/deps
    depends_on:
      - db
    entrypoint: ./entrypoint.sh
  
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
  mix_deps: